### ISSUE TITLE
Great library, what do you think of adding a adlib tracker player?

### ISSUE THREAD

**Issue by bleuge** [mills32/Little-Game-Engine-for-VGA-EGA#1]
There are great trackers out there for opl adlib music, example: http://www.adlibtracker.net/downloads.php
maybe it could be added a player lib for some of these trackers. What do you think?

**Comment by mills32** [comment]
Sorry for the late reply.
I was thinking about adding some adlib tracker support, but all the sources I found, required 386 and were not very fast. I wanted the adlib to be fast for the 8086 cpus (MOD is very slow even if you have a gravis ultrasound card), so I found an imf player, which is the simplest way to play adlib music (even if you have to convert the file to imf first).
I'll take a look to the adlib tracker source, but I think it requires 386.

> There are great trackers out there for opl adlib music, example: http://www.adlibtracker.net/downloads.php
> maybe it could be added a player lib for some of these trackers. What do you think?

Sorry for the late reply.
I was thinking about adding some adlib tracker support, but all the sources I found, required 386 and were not very fast. I wanted the adlib to be fast for the 8086 cpus (MOD is very slow even if you have a gravis ultrasound card), so I found an imf player, which is the simplest way to play adlib music (even if you have to convert the file to imf first).
I'll take a look to the adlib tracker source, but I think it requires 386.

**Comment by mills32** [comment]
I added vgm support. vgm files created with furnace tracker will work. So it is just like having tracker support on the engine. Music files can't be too long because they have to be smaller than 64KB. I won't add any other format because I still want this to work well on 8088's.
