### ISSUE TITLE
Problem with compiling

### ISSUE THREAD

**Issue by solniczka143** [mills32/Little-Game-Engine-for-VGA-EGA#6]
I have hard time compiling code. I don't know whats wrong. Please Help. 

Make.bat tcc output:
Turbo C++ Version 3.00 Copyright (c) 1992 Borland International
lt_sys.c:
lt_key.c:
lt_gfx.c:
Error lt_gfx.c 610: Type mismatch in redeclaration of 'LT_WaitVsync'
Error lt_gfx.c 1849: Type mismatch in redeclaration of 'LT_Load_Tiles'
Error lt_gfx.c 3256: Type mismatch in redeclaration of 'LT_Scroll_Map'
Warning lt_gfx.c 3674: 'i' is assigned a value that is never used in function LT_Fade_out_EGA
Warning lt_gfx.c 3734: 'i' is assigned a value that is never used in function LT_Fade_out_TGA
*** 3 errors in Compile ***
lt_spr.c:
Error lt_spr.c 558: Undefined symbol 'tga_sprite_data_offset' in function LT_Load_Sprite
Warning lt_spr.c 1189: 'y' is assigned a value that is never used in function LT_Draw_Sprites
Error lt_spr.c 1387: Undefined symbol 'tga_sprite_data_offset' in function LT_Draw_Sprites_TGA
*** 2 errors in Compile ***
lt_sound.c:
main.c:
Error main.c 235: Undefined symbol 'LT_MUSIC_MODE' in function Display_Intro
Error main.c 235: Too few parameters in call to 'LT_Load_Music' in function Display_Intro
Error main.c 236: Too few parameters in call to 'LT_Load_Music' in function Display_Intro
Error main.c 252: Undefined symbol 'LT_Text_Mode_BG' in function Display_Intro
Error main.c 253: Undefined symbol 'LT_Text_Mode_FG' in function Display_Intro
Warning main.c 327: 'Adlib_PacMan_Sound' is assigned a value that is never used in function Display_Intro
Warning main.c 327: 'Adlib_Bell_Sound' is assigned a value that is never used in function Display_Intro
Error main.c 332: Undefined symbol 'LT_MUSIC_MODE' in function Load_TopDown
Error main.c 332: Too few parameters in call to 'LT_Load_Music' in function Load_TopDown
Error main.c 333: Too few parameters in call to 'LT_Load_Music' in function Load_TopDown
Error main.c 420: Undefined symbol 'LT_MUSIC_MODE' in function Load_Platform
Error main.c 420: Too few parameters in call to 'LT_Load_Music' in function Load_Platform
Error main.c 421: Too few parameters in call to 'LT_Load_Music' in function Load_Platform
Error main.c 580: Too few parameters in call to 'LT_Load_Music' in function Load_Platform1
Error main.c 655: Too few parameters in call to 'LT_Load_Music' in function Load_Puzzle
Error main.c 746: Too few parameters in call to 'LT_Load_Music' in function Load_Shooter
*** 14 errors in Compile ***

        Available memory 3829560

**Comment by danipardo** [comment]
It looks like the commit 0223d from 8 July broke it, maybe a missing commit? If you checkout commit  cbfeb, then it will compile correctly. 
But again, I'd bet @mills32 forgot to upload something?

**Comment by solniczka143** [comment]
Thanks commit cbfeb from 16 July works!

**Comment by mills32** [comment]
Sorry,  I made some changes and I did not check it. It is probably a silly renamed function, I'll check it later
